[package]
name = "ds_in_rs"
version = "0.1.0"
authors = ["Siddhant Sharma <sharmasiddhant301@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
